### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by iwatakeshi** [mr-doc/mr-doc-theme-default#2]
@FGRibreau We'll need to rename the repo and republish it on npm as `mrdoc-theme-default` or as `doc-theme-default`. I'll definitely add to the repo that the former has been deprecated in favor of the latter.

**Comment by FGRibreau** [comment]
Ok, just tell me when you want to rename this one to "mrdoc-theme-default" :)

**Comment by iwatakeshi** [comment]
@FGRibreau I'm ready when you are :) The `doxx-default-theme` package should display a deprecated message according to the [API](https://docs.npmjs.com/cli/deprecate).

**Comment by iwatakeshi** [comment]
Closing this issue :)
