### ISSUE TITLE
Release 1.3.0

### ISSUE THREAD

**Issue by iwatakeshi** [mr-doc/mr-doc-theme-default#5]
I bumped the minor to fix the version gaps. I also used `npm-release` but of course I'll leave the npm publishing to you since it doesn't work haha. :)

**Comment by iwatakeshi** [comment]
@FGRibreau Could you also add me as a collaborator on npm for this package? :) I couldn't get it published on npm. :)

**Comment by FGRibreau** [comment]
@iwatakeshi done! :) (I forgot sorry)

**Comment by iwatakeshi** [comment]
:+1: No problem :)
